/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nhlahla Novela
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;


public class HedgeYourBetUsingFile extends javax.swing.JFrame {
   
    int questionNumber = 1;
int score = 0;
int previousScore = 0;
boolean questionSubmitted = false;

String fileName = "HedgeYourBetScore.txt";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HedgeYourBetUsingFile.class.getName());

    /**
     * Creates new form HedgeYourBetUsingFile
     */
    public HedgeYourBetUsingFile() {
        initComponents();
        
        loadPreviousScore();

    lblScore.setText("Previous Score: " + previousScore);
    }
        private void loadPreviousScore() {

        File file = new File(fileName);

        if (!file.exists()) {
            previousScore = 0;
            return;
        }

        try {

            Scanner input = new Scanner(file);

            if (input.hasNextInt()) {
                previousScore = input.nextInt();
            } else {
                previousScore = 0;
            }

            input.close();

        } catch (FileNotFoundException e) {

            previousScore = 0;
        }
    }
            private void saveScore() {

        try {

            PrintWriter output = new PrintWriter(fileName);

            output.println(score);

            output.close();

        } catch (FileNotFoundException e) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error saving score."
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnButton = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("HEDGE YOUR BET");

        lblQuestion.setText("Question 1: What is the capital of France?");

        chk1.setText("Paris");

        chk2.setText("London");

        chk3.setText("Rome");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        btnButton.setText("Next");
        btnButton.addActionListener(this::btnButtonActionPerformed);

        lblScore.setText("Previous Score: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chk1)
                                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chk2)
                                .addComponent(chk3)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnSubmit)
                            .addGap(43, 43, 43)
                            .addComponent(btnButton)
                            .addGap(57, 57, 57)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk3)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
                                          
 if (questionSubmitted) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "You have already submitted this question. Click Next.");
        return;
 }
    int selected = 0;
    

    if (chk1.isSelected()) selected++;
    if (chk2.isSelected()) selected++;
    if (chk3.isSelected()) selected++;

    // QUESTION 1 - Correct: Paris
    if (questionNumber == 1) {
        if (chk1.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 2 - Correct: Rome
    else if (questionNumber == 2) {
        if (chk3.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 3 - Correct: London
    else if (questionNumber == 3) {
        if (chk2.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 4 - Correct: Paris
    else if (questionNumber == 4) {
        if (chk1.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 5 - Correct: Rome
    else if (questionNumber == 5) {

        if (chk3.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }

        // SAVE THE FINAL SCORE TO THE FILE
        saveScore();

        String feedback;

        if (score > 21) {
            feedback = "Fantastic!";
        } else if (score > 15) {
            feedback = "Very good";
        } else {
            feedback = "OK";
        }

        lblScore.setText(
            "<html><center>FINAL SCORE: " + score +
            " / 25<br>FEEDBACK: " + feedback +
            "</center></html>"
        );

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "FINAL SCORE: " + score + " / 25\n" +
            "FEEDBACK: " + feedback
        );

        btnSubmit.setEnabled(false);
        btnButton.setEnabled(false);

        return;
    }

    questionSubmitted = true;
    lblScore.setText("Score: " + score);

    chk1.setSelected(false);
    chk2.setSelected(false);
    chk3.setSelected(false);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonActionPerformed
        if (questionNumber == 1) {

    questionNumber = 2;

    lblQuestion.setText(
        "Question 2: What is the capital of Italy?"
    );

} else if (questionNumber == 2) {

    questionNumber = 3;

    lblQuestion.setText(
        "Question 3: What is the capital of England?"
    );

} else if (questionNumber == 3) {

    questionNumber = 4;

    lblQuestion.setText(
        "Question 4: Which city is famous for the Eiffel Tower?"
    );

} else if (questionNumber == 4) {

    questionNumber = 5;

    lblQuestion.setText(
        "Question 5: Which city is famous for the Colosseum?"
    );

} else {

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "This is the last question. Click Submit to finish."
    );

    return;
}

chk1.setText("Paris");
chk2.setText("London");
chk3.setText("Rome");

chk1.setSelected(false);
chk2.setSelected(false);
chk3.setSelected(false);

questionSubmitted = false;
    }//GEN-LAST:event_btnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HedgeYourBetUsingFile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
