/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nhlahla Novela
 */
public class HedgeYourBet extends javax.swing.JFrame {
 
   int questionNumber = 1;
   int score = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HedgeYourBet.class.getName());

    /**
     * Creates new form HedgeYourBet
     */
    public HedgeYourBet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        btnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("HEDGE YOUR BET");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lblQuestion.setText("Question 1: What is the capital of France?");

        chk1.setText("Paris");

        chk2.setText("London");

        chk3.setText("Rome");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        lblScore.setText("Score:");

        btnButton.setText("Next");
        btnButton.addActionListener(this::btnButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(43, 43, 43)
                .addComponent(btnButton)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblQuestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk1)
                            .addComponent(chk2)
                            .addComponent(chk3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk3)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnButton))
                .addGap(40, 40, 40)
                .addComponent(lblScore)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed


    int selected = 0;

    if (chk1.isSelected()) selected++;
    if (chk2.isSelected()) selected++;
    if (chk3.isSelected()) selected++;

    // QUESTION 1 - Correct: Paris
    if (questionNumber == 1) {
        if (chk1.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 2 - Correct: Rome
    else if (questionNumber == 2) {
        if (chk3.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 3 - Correct: London
    else if (questionNumber == 3) {
        if (chk2.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 4 - Correct: Paris
    else if (questionNumber == 4) {
        if (chk1.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }
    }

    // QUESTION 5 - Correct: Rome
    else if (questionNumber == 5) {
        if (chk3.isSelected()) {
            if (selected == 1) score += 5;
            else if (selected == 2) score += 2;
            else if (selected == 3) score += 1;
        }

        String feedback;

        if (score > 21) {
            feedback = "Fantastic!";
        } else if (score > 15) {
            feedback = "Very good";
        } else {
            feedback = "OK";
        }

        lblScore.setText(
            "<html><center>FINAL SCORE: " + score +
            " / 25<br>FEEDBACK: " + feedback +
            "</center></html>"
        );

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "FINAL SCORE: " + score + " / 25\n" +
            "FEEDBACK: " + feedback
        );

        btnSubmit.setEnabled(false);
        btnButton.setEnabled(false);
        return;
    }

    lblScore.setText("Score: " + score);

    chk1.setSelected(false);
    chk2.setSelected(false);
    chk3.setSelected(false);

    

        

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonActionPerformed


    if (questionNumber == 1) {
        questionNumber = 2;

        lblQuestion.setText(
            "Question 2: What is the capital of Italy?"
        );

    } else if (questionNumber == 2) {
        questionNumber = 3;

        lblQuestion.setText(
            "Question 3: What is the capital of England?"
        );

    } else if (questionNumber == 3) {
        questionNumber = 4;

        lblQuestion.setText(
            "Question 4: Which city is famous for the Eiffel Tower?"
        );

    } else if (questionNumber == 4) {
        questionNumber = 5;

        lblQuestion.setText(
            "Question 5: Which city is famous for the Colosseum?"
        );

    } else if (questionNumber == 5) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "You are already on the final question.\nClick Submit to finish."
        );
        return;
    }

    chk1.setText("Paris");
    chk2.setText("London");
   chk3.setText("Rome");

    chk1.setSelected(false);
    chk2.setSelected(false);
    chk3.setSelected(false);

    }//GEN-LAST:event_btnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HedgeYourBet().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
